# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1de127db48424312eaaab4453c7123f9cd40dc159a2381f389c5637e5a979497e432ad3f2d4cca96b1c241aaf96e055fe451e4656385d14697a8f546b7a0c2e5

test:
  secret_key_base: 0a279806d43adf3df86b4dd0950589c433fb87dd246f87bbea041920f242de4c3fc728baa3b6719c060ac0b1cc606caee99d10ca767c3572a3ee7f04666fda3c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
